"""add field for type and photo

Revision ID: 20f56907f5f1
Revises: 
Create Date: 2024-04-20 13:47:42.291485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f56907f5f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('type', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('photo', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'photo')
    op.drop_column('questions', 'type')
    # ### end Alembic commands ###
